### ISSUE TITLE
Incompatible with latest version of KMER

### ISSUE THREAD

**Issue by marchoeppner** [qichao1984/GSMer#1]
Hi,

I wanted to test your GSMer tool, but I think it dies during the mapMer stage. MapMer now has a compulsory flag to specify the output format (I also submitted a related bug, which has since been fixed: http://sourceforge.net/p/kmer/bugs/31/). 

Could you perhaps check to make sure that GSMer is compatible with the latest release of Kmer? Thanks!

/Marc

**Comment by qichao1984** [comment]
Thanks for letting me know! This issue should have been fixed.
